name: bracket_buddy
version: 1.0.0+1
publish_to: none
description: Bracket Buddy is a versatile application designed to facilitate bracket pairing and round-robin 'all play all' competitions.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  english_words: ^4.0.0
  flutter_spinkit: ^5.2.0
  gap: ^3.0.1
  nb_utils: ^6.1.2
  basic_utils: ^5.7.0
  scrollable: ^1.0.5
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  firebase_crashlytics: ^3.4.9
  firebase: ^9.0.3
  firebase_analytics: ^10.8.0
  firebase_core: ^2.24.2
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.0

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_test: 
    sdk: flutter
  isar_generator: ^3.1.0+1

dependency_overrides:
  vm_service:  14.0.0  
  http: ^1.2.1

flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/avatars/
    - assets/icons/
    - assets/animation/
    - .env

flutter_native_splash:
  color: "#29B026"
#  image: assets/logo/logo_transparent.png

  android_12:
#    image: assets/logo/BluePOS_android.png
    color: "#29B026"