allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

def buildRoot = new File(rootProject.projectDir.parentFile, 'build')
subprojects {
    layout.buildDirectory.set(file("${buildRoot}/${project.name}"))
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

tasks.register("clean", Delete) {
    delete buildRoot
}
