// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-HUwafwLHea4GlRRv0TeNC9nUFGxVpm4',
    appId: '1:598237160277:ios:2d02f360fd2340607f05dc',
    messagingSenderId: '598237160277',
    projectId: 'bracket-buddy-7a8c4',
    storageBucket: 'bracket-buddy-7a8c4.firebasestorage.app',
    iosBundleId: 'dev.richardoppong.bracketBuddy',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtVkpwBbgMMIa46uotN_JixLwK1MuQyH8',
    appId: '1:598237160277:android:ddf078e435950d6c7f05dc',
    messagingSenderId: '598237160277',
    projectId: 'bracket-buddy-7a8c4',
    storageBucket: 'bracket-buddy-7a8c4.firebasestorage.app',
  );

}